# Generated by Django 5.0.2 on 2024-03-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_repeate',
            new_name='is_repeated',
        ),
    ]
